# -*- coding: utf-8 -*-
"""exercicio2_fila_simulacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7MgKEHDNxRuPEoF9Fdhi6qtzfgP98qN
"""

class Fila:

  def __init__(self):
    self.sequencia = [1, 2, 3, 4]
    self.fila = []
    self.remocao = []

  def adicionar(self, valor=None):
    if valor is None:
      for i in self.sequencia:
        self.fila.append(i)
    else:
      self.fila.append(valor)

  def saida(self):
    while len(self.fila) > 0:
      self.frente = self.fila.pop(0)
      self.remocao.append(self.frente)
    return self.remocao

user = Fila()

user.adicionar()

print(user.saida())