# -*- coding: utf-8 -*-
"""exercicio1_inversao_string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZEzCqyLWzgIwYRuBVNb29u3-vqU8FN7
"""

class Pilha:
  def __init__(self):
    self.pilha = []
    self.remocao = []

  def adicionar(self, valor):
    self.pilha.append(valor)

  def saida(self):
    while len(self.pilha) > 0:
        self.remocao.append(self.pilha.pop())
    return ''.join(self.remocao)

user = Pilha()

for caractere in "Hello":
  user.adicionar(caractere)

print(user.saida())